Final Project/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Final_Project.Models;
using Final_Project.ViewModels;
using Final_Project.Repository;
using Final_Project.ViewModelRepository;

namespace Final_Project.Controllers
{
    [Authorize(Roles ="Admin,SV")]
    public class DashboardController : Controller
    {
        IProductRepository ProductRepository;
        IDepartmentRepository departmentRepository;
        IProductWithDepartmentName productWithDepartmentNameRepository;
        public DashboardController(IProductRepository _productRepository,IDepartmentRepository _departmentRepository,IProductWithDepartmentName _p) {
        
        this.ProductRepository = _productRepository;
            this.departmentRepository = _departmentRepository;
            productWithDepartmentNameRepository = _p;
        }
        public IActionResult Index()
        {
          
            return View(productWithDepartmentNameRepository.GetAll());
        }
        public IActionResult MangingDepartment()
        {
 
            return View(departmentRepository.GetAll());
        }

        [AllowAnonymous]
        public IActionResult Search(string query)
        {

            if (query != null)
            {

                List<ProductsWithDepartmentName> prod = productWithDepartmentNameRepository.Search(query);
                return View("Index", prod);

            }
            else
            {
                List<ProductsWithDepartmentName> prod = productWithDepartmentNameRepository.GetAll();
                return View("Index", prod);

            }
        }
        [AllowAnonymous]
        public IActionResult SearchDepartment(string query)
        {

            if (query != null)
            {

                List<Department> prod = departmentRepository.Search(query);
                return View("MangingDepartment", prod);

            }
            else
            {
                List<Department> prod = departmentRepository.GetAll();
                return View("MangingDepartment", prod);

            }
        }
    }
}

Final Project/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Final_Project.Models;
using Final_Project.Repository;
using Final_Project.ViewModelRepository;
using System.Data;
using System.Runtime.Intrinsics.Arm;

namespace Final_Project.Controllers
{
    public class DepartmentController : Controller
    {
      
        IProductRepository ProductRepository;
        IDepartmentRepository departmentRepository;
        IProductWithDepartmentName productWithDepartmentNameRepository;

       
        public DepartmentController(IProductRepository prodRepo, IDepartmentRepository DeptRepo,IProductWithDepartmentName _p)
        {
            departmentRepository = DeptRepo;
            ProductRepository = prodRepo;
            productWithDepartmentNameRepository = _p;

        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewData["ProductsList"] = productWithDepartmentNameRepository.GetAll();
            List<Department> deptListModel = departmentRepository.GetAll();
            return View(deptListModel);

        }
        [AllowAnonymous]
        public IActionResult GetById(int id)
        {

            Department deptModel = departmentRepository.GetdeptById(id);
            ViewData["id"]=id;
            return View(deptModel);

        }

        [HttpGet]
        [Authorize(Roles = "Admin,SV")]
        public IActionResult New()
        {
           
            return View(new Department());
        }
        [HttpPost]//Form 
        [Authorize(Roles = "Admin,SV")]
        public IActionResult SaveAdd(Department dept)
        {
            if (ModelState.IsValid&&dept!=null)
            {
                try
                {
                    departmentRepository.Add(dept);
                    departmentRepository.Save();
                    return RedirectToAction("MangingDepartment","Dashboard");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message.ToString());
                }
            }
            return View("New", dept);
        }

        [Authorize(Roles = "Admin,SV")]
        public IActionResult Edit(int id)
        {

            Department prodmodel = departmentRepository.GetdeptById(id);
                //db.Departments.FirstOrDefault(I => I.Id == id);
            //ViewData["prodtList"] = db.Products.ToList();
            return View(prodmodel);

        }

        [HttpPost]
        [Authorize(Roles = "Admin,SV")]
        public IActionResult SaveEdit(int id, Department newdept)
        {

            if (ModelState.IsValid&&newdept!=null)
            {

                Department olddept = departmentRepository.GetdeptById(id);
                if (olddept != null)
                {
                    departmentRepository.Update(newdept, id);
                    departmentRepository.Save();
                    return RedirectToAction("MangingDepartment", "Dashboard");

                }
            }
            //ViewData["prodList"] = db.Products.ToList();
            return View("Edit", newdept);
        }

        [Authorize(Roles = "Admin,SV")]
        public IActionResult Remove(int id)
        {

            departmentRepository.Delete(id);
            departmentRepository.Save();
            return RedirectToAction("MangingDepartment", "Dashboard");
        }

        [AllowAnonymous]
        public IActionResult PartialProductResult(int deptId)
        {

            List<Product> product = ProductRepository.GetProductByDeptId(deptId);

            return PartialView("_ShowAllProudctsPartial",product);
        }

    }
}

Final Project/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Final_Project.Models;
using Final_Project.Repository;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Admin,SV")]
    public class ProductController : Controller
    {
       
        IProductRepository ProductRepository;
        IDepartmentRepository departmentRepository;

     

        public ProductController(IProductRepository prodRepo, IDepartmentRepository DeptRepo)
        {
            departmentRepository = DeptRepo;
            ProductRepository = prodRepo;

        }

        [AllowAnonymous]

        public IActionResult Index()
        {
            
            List<Product> prodListModel = ProductRepository.GetAll();
            return View(prodListModel);

        }
        [AllowAnonymous]

        public IActionResult GetById(int id)
        {

            Product prodModel = ProductRepository.GetProductById(id);
            return View(prodModel);

        }

        [HttpGet]
        public IActionResult New()
        {
            ViewData["DeptList"] = departmentRepository.GetAll();
            return View(new Product());
        }
        [HttpPost]//Form 
        public IActionResult SaveAdd(Product prod, IFormFile imageFile)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    ProductRepository.Add(prod,imageFile);
                    ProductRepository.Save();
                    return RedirectToAction("Index", "Dashboard");
                }
                catch (Exception ex)
                {


                    ModelState.AddModelError(string.Empty, ex.Message.ToString());

                }

            }

            ViewData["DeptList"] = departmentRepository.GetAll();
            return View("New", prod);

        }

        public IActionResult Edit(int id)
        {

            Product prodmodel = ProductRepository.GetProductById(id);
                //db.Products.FirstOrDefault(I => I.Id == id);
            ViewData["DeptList"] = departmentRepository.GetAll();
                //db.Departments.ToList();
            return View("Edit",prodmodel);
        }

        [HttpPost]
        public IActionResult SaveEdit(int id, Product newprod , IFormFile? imageFile)
        {
             Product oldcrs = ProductRepository.GetProductById(id);
            if (ModelState.IsValid)
            {
                if (oldcrs != null)
                {
                    ProductRepository.Update(newprod, id,imageFile);
                    ProductRepository.Save();
                    return RedirectToAction("Index", "Dashboard");

                }
            }
            ViewData["DeptList"] = departmentRepository.GetAll();
            return View("Edit", newprod);
        }
        public IActionResult Remove(int id)
        {

            ProductRepository.Delete(id);
            ProductRepository.Save();
            return RedirectToAction("Index", "Dashboard");
        }
        [AllowAnonymous]
        public IActionResult Search(string query)
        {

           if (query != null )
            {

            List<Product> prod = ProductRepository.Search(query);
            return View("Index", prod);

            }else{
                List<Product> prod = ProductRepository.GetAll();
                return View("Index",prod);
          
                }
        }

        [AllowAnonymous]
        public IActionResult GetProdByDept(int deptid)
        {
            List<Product> prod = ProductRepository.GetProductByDeptId(deptid);
            return View("Index",prod);
        }

    }
}

Final Project/Views/Dashboard/Index.cshtml
@model List<ProductsWithDepartmentName>
@{
    ViewData["Title"] = "Index";

    //Layout = "_ProductsLayout";
}

<div class="category-top box-style">

    <form class="search-form" action="/Dashboard/Search" method="post">
        <div class="input-group">
            <input type="text" class="form-control" name="query" placeholder="Search" required>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>
@Html.ActionLink("Add New Product", "New", "Product",null,new{@class="btn btn-outline-success"})
<br />
<br />
<table class="table table-bordered text-center">
    <thead>
        <tr>
            
            <td>Name</td>
            <td>Price</td>
            <td>Img</td>
            <td>Description</td>
            <td>Department Name</td>
            <td>Action</td>
            
        </tr>
    </thead>
    @foreach (ProductsWithDepartmentName item in Model)
    {
        <tr>
            <td>@item.ProductName</td>
            <td>@item.Price</td>
            <td><img src="/images/@item.Img" style="width:100px;height:100px" /></td>
            <td>@item.Description</td>
            <td>@item.DepartmentName</td>
            <td>
                @Html.ActionLink("Remove", "Remove","Product", new { id = item.Id } ,
            new { @class = "btn btn-outline-danger",
            onclick = $"return confirm('Are you sure you want to delete {item.ProductName} form Products?')"
            })
                <a class="btn btn-outline-warning" href="/Product/edit/@item.Id">Edit</a>
            </td>
        </tr>


    }

</table>

@section Nav{
    <li class="nav-item">
        <a class="text-danger fw-bold m-2 active" asp-controller="Department" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
        <a class="text-danger fw-bold m-2" asp-controller="Product" asp-action="Index">Shop</a>
    </li>
}

Final Project/Views/Dashboard/MangingDepartment.cshtml
@model List<Department>
@{
    ViewData["Title"] = "Index";


}



<div class="category-top box-style">
    <form class="search-form" action="/Dashboard/SearchDepartment" method="post">
        <div class="input-group">
            <input type="text" class="form-control" name="query" placeholder="Search" required>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </form>
</div>

@Html.ActionLink("Add New Department", "New", "Department",null,new{@class="btn btn-outline-success"})
<br />
<br />
<table class="table table-bordered text-center">
    <thead>
        <tr>

            <td>Name</td>
            <td>Icon</td>
            <td>Manger Name</td>
            <td>Action</td>   

        </tr>
    </thead>
    @foreach (Department item in Model)
    {
        <tr>
            <td>@item.DepartmentName</td>
            <td><i class="lni lni-@item.DepartmentIcon"></i></td>
            <td>@item.DeptManger</td>
            <td>
                @Html.ActionLink("Remove", "Remove","Department", new { id = item.Id } ,


            new { @class = "btn btn-danger",
            onclick = $"return confirm('Are you sure you want to delete {item.DepartmentName} form Department?')"
            })
                | <a class="btn btn-outline-warning" href="/Department/edit/@item.Id">Edit</a> |
                <a href="#" onclick="display(@item.Id)" class="btn btn-outline-secondary">Show All Products</a>
            </td>
        </tr>


    }

</table>
<br />
<br />
<br />
<div id="TCPartilal" class="m-auto">
</div>
<br />
<br />
<br />

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        function display(deptId) {
            event.preventDefault();
            $.ajax({
                url: "/Department/PartialProductResult",
                data: { deptId: deptId },
                success: function (result) {
                    $('#TCPartilal').html(result);
                }
            });
        }
    </script>
}
@section Nav{
    <li class="nav-item">
        <a class="text-danger fw-bold m-2" asp-controller="Department" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
        <a class="text-danger fw-bold m-2" asp-controller="Product" asp-action="Index">Shop</a>
    </li>
}